# Generated by Django 5.2.8 on 2025-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('userHealth', models.IntegerField()),
                ('userAmmo', models.IntegerField()),
                ('userHighscroe', models.IntegerField()),
                ('userFirstTime', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
            ],
        ),
    ]
